title: Seu Título Aqui
description: Uma breve descrição do seu site
baseurl: ""
url: "https://pauloguedes2.github.io"

theme: minima

plugins:
  - jekyll-feed


author:
  name: Paulo Guedes

markdown: kramdown
